[project]
name = "calibre-ark-metadata-source"
version = "0.1.0"
description = "Add your description here"
readme = "README.rst"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = []
